<?xml version="1.0" encoding="UTF-8"?>
<!--
  LOCAL OVERRIDE of the HL7 base template's createArtifactSummary.xslt.
  See ../README.md for what changed and why. Diff against createArtifactSummary.xslt.orig.

  Two changes from the original:
    * content starts at h2, not h3, so the CSS section counter increments and headings number
      2.1 / 2.1.1 rather than 2.0.1
    * each grouping is subdivided by resource TYPE, read from resource.reference.reference, giving
      a second level that the flat definition.grouping structure cannot express on its own

  The type subheadings are NOT sorted — they follow the order the resources appear in
  definition.resource, which is the order scripts/make-groups.js writes them in. That script orders
  by type on purpose (the plan before the activities it is built from); sorting here would override
  it with alphabetical order.
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:html="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://hl7.org/fhir">
  <xsl:output method="xml" encoding="utf-8" indent="yes" omit-xml-declaration="yes"/>
  <xsl:param name="columns" select="3"/>
  <xsl:param name="version"/>
  <xsl:param name="globals"/>

  <!-- Muenchian grouping: resources keyed by grouping + resource type. XSLT 1.0 has no
       for-each-group, and a node-set held in a variable becomes a result tree fragment that
       cannot be iterated, so a key is the only way to partition within a grouping. -->
  <xsl:key name="resByGroupType" match="f:resource"
           use="concat(f:groupingId/@value, '|', substring-before(f:reference/f:reference/@value, '/'))"/>

  <xsl:template match="f:ImplementationGuide">
    <xsl:comment>DO NOT EDIT THIS FILE - it is generated from ig-template/scripts/createArtifactSummary.xslt</xsl:comment>
    <div class="markdown-toc">
      <p>Contents:</p>
      <ul>
        <xsl:if test="$globals='Y'">
          <li>
            <a href="#globals">Globals</a>
          </li>
        </xsl:if>
        <xsl:for-each select="f:definition/f:grouping">
          <xsl:variable name="gid" select="@id"/>
          <xsl:if test="parent::f:definition/f:resource[f:groupingId/@value=$gid][f:extension[@url='http://hl7.org/fhir/StructureDefinition/implementationguide-page']]">
            <li>
              <a href="#{position()}">
                <xsl:value-of select="f:name/@value"/>
              </a>
              <!-- nested contents, one entry per resource type in this grouping -->
              <ul>
                <xsl:for-each select="parent::f:definition/f:resource[f:groupingId/@value=$gid][f:extension[@url='http://hl7.org/fhir/StructureDefinition/implementationguide-page']][generate-id() = generate-id(key('resByGroupType', concat($gid, '|', substring-before(f:reference/f:reference/@value, '/')))[f:extension[@url='http://hl7.org/fhir/StructureDefinition/implementationguide-page']][1])]">
                  <xsl:variable name="type" select="substring-before(f:reference/f:reference/@value, '/')"/>
                  <li>
                    <a href="#{$gid}-{$type}">
                      <xsl:value-of select="$type"/>
                    </a>
                  </li>
                </xsl:for-each>
              </ul>
            </li>
          </xsl:if>
        </xsl:for-each>
      </ul>
    </div>
    <div>
      <p>This page provides a list of the FHIR artifacts defined as part of this implementation guide.</p>
      <xsl:if test="$globals='Y'">
        <a name="globals">
          <xsl:value-of select="' '"/>
        </a>
        <h2>Global profiles</h2>
        {% include globals-table.xhtml %}
      </xsl:if>
      <xsl:for-each select="f:definition/f:grouping">
        <xsl:variable name="gid" select="@id"/>
        <xsl:variable name="relevant"
                      select="parent::f:definition/f:resource[f:groupingId/@value=$gid][f:extension[@url='http://hl7.org/fhir/StructureDefinition/implementationguide-page']][not(f:extension[@url='http://hl7.org/fhir/StructureDefinition/tools-alternateVersion'] or $version) or (f:extension[@url='http://hl7.org/fhir/StructureDefinition/tools-alternateVersion']/f:valueCode/@value=$version)]"/>
        <xsl:if test="$relevant">
          <a name="{position()}">
            <xsl:value-of select="' '"/>
          </a>
          <h2>
            <xsl:value-of select="concat(f:name/@value, ' ')"/>
          </h2>
          <xsl:text>{% capture grouping_desc %}</xsl:text>
          <xsl:value-of select="f:description/@value" disable-output-escaping="no"/>
          <xsl:text>{% endcapture %}
    {{ grouping_desc | markdownify}}</xsl:text>
          <!-- one h3 and one table per resource type within this grouping -->
          <xsl:for-each select="$relevant[generate-id() = generate-id(key('resByGroupType', concat($gid, '|', substring-before(f:reference/f:reference/@value, '/')))[f:extension[@url='http://hl7.org/fhir/StructureDefinition/implementationguide-page']][1])]">
            <xsl:variable name="type" select="substring-before(f:reference/f:reference/@value, '/')"/>
            <a name="{$gid}-{$type}">
              <xsl:value-of select="' '"/>
            </a>
            <h3>
              <xsl:value-of select="concat($type, ' ')"/>
            </h3>
            <xsl:call-template name="resourceTable">
              <xsl:with-param name="rows" select="key('resByGroupType', concat($gid, '|', $type))[f:groupingId/@value=$gid][f:extension[@url='http://hl7.org/fhir/StructureDefinition/implementationguide-page']]"/>
            </xsl:call-template>
          </xsl:for-each>
        </xsl:if>
      </xsl:for-each>
    </div>
  </xsl:template>

  <xsl:template name="resourceTable">
    <xsl:param name="rows"/>
    <xsl:variable name="showDescriptions" select="count($rows/f:description/@value)!=0"/>
    <table class="grid">
      <col style="width:20%"/>
      <tbody>
        <xsl:for-each select="$rows">
          <xsl:sort select="f:name/@value"/>
          <tr>
            <td style="column-width:30%">
              <a href="{f:extension[@url='http://hl7.org/fhir/StructureDefinition/implementationguide-page']/f:valueUri/@value}" title="{f:reference/f:reference/@value}">
                <xsl:choose>
                  <xsl:when test="f:name">
                    <xsl:value-of select="f:name/@value"/>
                  </xsl:when>
                  <xsl:otherwise>
                    <xsl:value-of select="f:reference/f:reference/@value"/>
                  </xsl:otherwise>
                </xsl:choose>
              </a>
            </td>
            <xsl:if test="$showDescriptions">
              <td>
                <xsl:text>{% capture desc %}</xsl:text>
                <xsl:value-of select="f:description/@value" disable-output-escaping="no"/>
                <xsl:text>{% endcapture %}
{{ desc | markdownify}}</xsl:text>
              </td>
            </xsl:if>
          </tr>
        </xsl:for-each>
      </tbody>
    </table>
  </xsl:template>
</xsl:stylesheet>
